package:
  name: caastools
  version: 1.0.0

source:
  path: .

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - r-base=>3.6
    - setuptools

  run:
    - python
    - r-base=>3.6
    - biopython=1.79
    - bioconda::dendropy=5.0.1
    - scipy=1.14.0
    - r-devtools=2.4.5
    - r-ape=5.8
    - r-tibble=3.2.1
    - r-readr=2.1.5

test:
  imports:
    - caastools.boot
    
  
about:
  home: https://github.com/IsGlak/caastools-in-conda