package:
  name: caastools
  version: 1.0.0

source:
#  git_rev: 1.0.0
#  git_url: https://github.com/IsGlak/caastools-in-conda/archive/refs/heads/main.zip
  path: ../
requirements:
  build:
    - python
    - r-base

  run:
    - python
    - r-base
    - biopython
    - bioconda::dendropy
    - scipy

test:
  imports:
#    - caastools
  
about:
  home: https://github.com/IsGlak/caastools-in-conda