package:
  name: caastools
  version: 1.0.0

source:
  git_rev: 1.0.0
  git_url: https://github.com/IsGlak/caastools-in-conda/archive/refs/heads/main.zip

requirements:
  build:
    - python
    - biopython
    - dendropy
    - scipy
    - itertools

  run:
    - python
    - biopython
    - dendropy
    - scipy
    - itertools

test:
  imports:
    - caastools

about:
  home: https://github.com/IsGlak/caastools-in-conda