package:
  name: caastools
  version: 1.0.0

source:
#  git_rev: 1.0.0
#  git_url: https://github.com/IsGlak/caastools-in-conda/archive/refs/heads/main.zip
  path: .

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - r-base
    - setuptools

  run:
    - python
    - r-base
    - biopython
    - bioconda::dendropy
    - scipy

test:
  imports:
    - caastools.boot
    
  
about:
  home: https://github.com/IsGlak/caastools-in-conda